// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}
