// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docker} from '../models';
import {ports} from '../models';
import {nodemodules} from '../models';
import {ssh} from '../models';

export function CancelNodeModulesScan():Promise<void>;

export function Cleanup(arg1:docker.CleanupOptions):Promise<docker.CleanupResult>;

export function KillProcess(arg1:number):Promise<void>;

export function ListChildProcesses(arg1:number):Promise<Array<ports.PortInfo>>;

export function ListContainerStats():Promise<Array<docker.ContainerStats>>;

export function ListContainers():Promise<Array<docker.ContainerInfo>>;

export function ListImages():Promise<Array<docker.ImageInfo>>;

export function ListPortOwners():Promise<Array<docker.PortOwner>>;

export function ListPorts():Promise<Array<ports.PortInfo>>;

export function LoadOlderContainerLogs(arg1:string,arg2:string,arg3:number):Promise<docker.OlderLogs>;

export function NodeModulesSize(arg1:string):Promise<number>;

export function PickDirectory():Promise<string>;

export function PickFile():Promise<string>;

export function PruneImages():Promise<docker.PruneResult>;

export function RemoveContainer(arg1:string):Promise<void>;

export function RemoveImage(arg1:string):Promise<void>;

export function RemoveNodeModules(arg1:Array<string>):Promise<Array<nodemodules.RemoveResult>>;

export function RestartContainer(arg1:string):Promise<void>;

export function SSHCloseTerminal(arg1:string,arg2:string):Promise<void>;

export function SSHConfirmHostKey(arg1:string,arg2:boolean):Promise<void>;

export function SSHConnect(arg1:ssh.HostSpec,arg2:string):Promise<ssh.ConnectResult>;

export function SSHDisconnect(arg1:string):Promise<void>;

export function SSHImportConfig():Promise<ssh.ImportResult>;

export function SSHOpenTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SSHResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SSHWrite(arg1:string,arg2:string):Promise<void>;

export function ScanNodeModules(arg1:string):Promise<nodemodules.ScanResult>;

export function StartContainer(arg1:string):Promise<void>;

export function StartContainerLogs(arg1:string,arg2:string,arg3:number):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopContainerLogs(arg1:string):Promise<void>;
