// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ports} from '../models';

export function KillProcess(arg1:number):Promise<void>;

export function ListPorts():Promise<Array<ports.PortInfo>>;
