// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelNodeModulesScan() {
  return window['go']['main']['App']['CancelNodeModulesScan']();
}

export function Cleanup(arg1) {
  return window['go']['main']['App']['Cleanup'](arg1);
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function ListChildProcesses(arg1) {
  return window['go']['main']['App']['ListChildProcesses'](arg1);
}

export function ListContainerStats() {
  return window['go']['main']['App']['ListContainerStats']();
}

export function ListContainers() {
  return window['go']['main']['App']['ListContainers']();
}

export function ListImages() {
  return window['go']['main']['App']['ListImages']();
}

export function ListPortOwners() {
  return window['go']['main']['App']['ListPortOwners']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function LoadOlderContainerLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadOlderContainerLogs'](arg1, arg2, arg3);
}

export function NodeModulesSize(arg1) {
  return window['go']['main']['App']['NodeModulesSize'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PruneImages() {
  return window['go']['main']['App']['PruneImages']();
}

export function RemoteCloseTunnel(arg1) {
  return window['go']['main']['App']['RemoteCloseTunnel'](arg1);
}

export function RemoteContainerAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteContainerAction'](arg1, arg2, arg3);
}

export function RemoteContainerNetworks(arg1, arg2) {
  return window['go']['main']['App']['RemoteContainerNetworks'](arg1, arg2);
}

export function RemoteKillProcess(arg1, arg2) {
  return window['go']['main']['App']['RemoteKillProcess'](arg1, arg2);
}

export function RemoteListContainers(arg1) {
  return window['go']['main']['App']['RemoteListContainers'](arg1);
}

export function RemoteListImages(arg1) {
  return window['go']['main']['App']['RemoteListImages'](arg1);
}

export function RemoteListPorts(arg1) {
  return window['go']['main']['App']['RemoteListPorts'](arg1);
}

export function RemoteListTunnels() {
  return window['go']['main']['App']['RemoteListTunnels']();
}

export function RemoteLoadOlderLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoteLoadOlderLogs'](arg1, arg2, arg3, arg4);
}

export function RemoteOpenTunnel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RemoteOpenTunnel'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoteRemoveImage(arg1, arg2) {
  return window['go']['main']['App']['RemoteRemoveImage'](arg1, arg2);
}

export function RemoteStartLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoteStartLogs'](arg1, arg2, arg3, arg4);
}

export function RemoteStopLogs(arg1) {
  return window['go']['main']['App']['RemoteStopLogs'](arg1);
}

export function RemoteSuggestLocalPort(arg1) {
  return window['go']['main']['App']['RemoteSuggestLocalPort'](arg1);
}

export function RemoveContainer(arg1) {
  return window['go']['main']['App']['RemoveContainer'](arg1);
}

export function RemoveImage(arg1) {
  return window['go']['main']['App']['RemoveImage'](arg1);
}

export function RemoveNodeModules(arg1) {
  return window['go']['main']['App']['RemoveNodeModules'](arg1);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function SSHAck(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHAck'](arg1, arg2, arg3);
}

export function SSHCloseTerminal(arg1, arg2) {
  return window['go']['main']['App']['SSHCloseTerminal'](arg1, arg2);
}

export function SSHConfirmHostKey(arg1, arg2) {
  return window['go']['main']['App']['SSHConfirmHostKey'](arg1, arg2);
}

export function SSHConnect(arg1, arg2) {
  return window['go']['main']['App']['SSHConnect'](arg1, arg2);
}

export function SSHDisconnect(arg1) {
  return window['go']['main']['App']['SSHDisconnect'](arg1);
}

export function SSHImportConfig() {
  return window['go']['main']['App']['SSHImportConfig']();
}

export function SSHOpenTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SSHOpenTerminal'](arg1, arg2, arg3, arg4);
}

export function SSHResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHResize'](arg1, arg2, arg3);
}

export function SSHWrite(arg1, arg2) {
  return window['go']['main']['App']['SSHWrite'](arg1, arg2);
}

export function ScanNodeModules(arg1) {
  return window['go']['main']['App']['ScanNodeModules'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartContainerLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartContainerLogs'](arg1, arg2, arg3);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopContainerLogs(arg1) {
  return window['go']['main']['App']['StopContainerLogs'](arg1);
}
